In [714]:
import numpy as np
import pandas as pd

In [715]:
df_main = pd.read_csv('/Users/habibaamir/Documents/Python/GDGC/car_data.csv')
np.set_printoptions(suppress=True)
df_main

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007.0,NaN,70000.0,Petrrol,NaN,Manual,First Owner
1,Maruti Wagon R LXI Minor,NaN,135000.0,50000.0,Petorl,Indvidual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012.0,600000.0,100000.0,Deisel,Indvidual,Manual,First Owner
3,Datsun RediGO T Option,2017.0,250000.0,46000.0,Petorl,Indivudal,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014.0,450000.0,141000.0,Diesl,Indivudal,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4340,NaN,2010.0,165000.0,80000.0,NaN,Indvidual,Manual,First Owner
4341,Renault KWID RXT BSIV,2019.0,250000.0,27000.0,NaN,Indvidual,Manual,First Owner
4342,Hyundai Santro Xing GL Plus,2008.0,120000.0,41723.0,Petorl,Indvidual,Manual,Second Owner
4343,Honda Amaze VX i-DTEC,2014.0,450000.0,141000.0,Deisel,Indvidual,Manual,Second Owner
4344,Mahindra TUV 300 T8 AMT,2016.0,730000.0,60000.0,Diesl,Indivudal,Automatic,Second Owner

In [716]:
df = df_main.copy()

In [717]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4345 entries, 0 to 4344
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4017 non-null   object
 1   year           4041 non-null   float64
 2   selling_price  4054 non-null   float64
 3   km_driven      4026 non-null   object
 4   fuel           4042 non-null   object
 5   seller_type    4056 non-null   object
 6   transmission   4040 non-null   object
 7   owner          4059 non-null   object
dtypes: float64(2), object(6)
memory usage: 271.7+ KB

In [718]:
df.duplicated().sum()

np.int64(112)

In [719]:
df.drop_duplicates(inplace=True)

In [720]:
df.isnull().sum()

name             326
year             303
selling_price    289
km_driven        319
fuel             299
seller_type      289
transmission     304
owner            284
dtype: int64

In [721]:
df.isnull().all(axis=1).sum()

np.int64(0)

In [722]:
for i in df:
    print(f"{df[i].describe()}\n\n")

count                       3907
unique                      1438
top       Maruti Swift Dzire VDI
freq                          63
Name: name, dtype: object


count    3930.000000
mean     2013.249109
std        16.779521
min      1800.000000
25%      2011.000000
50%      2014.000000
75%      2016.000000
max      3000.000000
Name: year, dtype: float64


count    3.944000e+03
mean     4.906879e+05
std      5.537800e+05
min     -1.200000e+05
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64


count        3914
unique        743
top       70000.0
freq          224
Name: km_driven, dtype: object


count      3934
unique        8
top       Diesl
freq        979
Name: fuel, dtype: object


count          3944
unique            5
top       Indivudal
freq           1512
Name: seller_type, dtype: object


count       3929
unique         2
top       Manual
freq        3530
Name: transmission, dtype: object


count            3949
unique              5
top       First Owner
freq             2562
Name: owner, dtype: object

In [723]:
print(df['fuel'].unique())
print(df['seller_type'].unique())
print(df['transmission'].unique())
df['owner'].unique()

['Petrrol' 'Petorl' 'Deisel' 'Diesl' 'Petrl' 'CNG' nan 'LPG' 'Electric']
[nan 'Indvidual' 'Indivudal' 'Deelar' 'Dealerr' 'Trustmark Dealer']
['Manual' nan 'Automatic']

array(['First Owner', 'Second Owner', nan, 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'], dtype=object)

In [724]:
df.dropna(subset=['name'], inplace=True)

In [725]:
new_fuel = {'Petrrol': 'Petrol', 
            'Petorl' : 'Petrol',
            'Petrl' : 'Petrol',
            'Deisel' : 'Diesel',
            'Diesl' : 'Diesel',
            'CNG' : 'CNG',
            'LPG' : 'LPG', 
            'Electric' : 'Electric'
}
df['fuel'] = df['fuel'].map(new_fuel)

In [726]:
print(df['fuel'].unique())

['Petrol' 'Diesel' 'CNG' nan 'LPG' 'Electric']

In [727]:
new_seller_type = {
    'Indvidual' : 'Individual',
    'Indivudal' : 'Individual',
    'Deelar' : 'Dealer',
    'Dealerr' : 'Dealer',
    'Trustmark Dealer' : 'Trustmark Dealer'
}
df['seller_type'] = df['seller_type'].map(new_seller_type)

In [728]:
print(df['seller_type'].unique())

[nan 'Individual' 'Dealer' 'Trustmark Dealer']

In [729]:
df[df['year'] < 1886]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
1651,Toyota Etios Cross 1.2L G,1800.0,320000.0,60000.0,Petrol,Individual,Manual,First Owner

1st invented cas was in 1886

In [730]:
df[df['year'] > 2026]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2866,Toyota Innova 2.5 G4 Diesel 7-seater,3000.0,350000.0,140000.0,Diesel,Individual,Manual,Second Owner
4037,Maruti Celerio VXI Optional,2050.0,430999.0,14000.0,NaN,Dealer,Manual,First Owner

In [731]:
df['year'] = df['year'].replace(1800, np.nan)
df['year'] = df['year'].replace(2050, np.nan)
df['year'] = df['year'].replace(3000, np.nan)

In [732]:
df['year'].describe()

count    3633.000000
mean     2013.034407
std         4.706610
min      1890.000000
25%      2011.000000
50%      2014.000000
75%      2016.000000
max      2020.000000
Name: year, dtype: float64

In [733]:
df[df['selling_price'] < 0]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
853,Hyundai Verna 1.6 SX VTVT AT,2011.0,-50000.0,60000.0,Petrol,Individual,Automatic,Third Owner
1741,Renault Duster 85PS Diesel RxL,2013.0,-9999.0,1000.0,Diesel,Dealer,Manual,Second Owner
2545,Tata Manza Aura (ABS) Quadrajet BS IV,2012.0,-4500.0,80000.0,Diesel,Individual,Manual,Second Owner
4094,Ford EcoSport 1.5 Petrol Titanium Plus AT BSIV,2015.0,-120000.0,48238.0,Petrol,Trustmark Dealer,Automatic,First Owner

In [734]:
df.loc[df['selling_price'] < 0 , 'selling_price'] = df['selling_price'].median()

In [735]:
df['selling_price'].describe()

count    3.634000e+03
mean     4.934202e+05
std      5.615647e+05
min      2.000000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

In [736]:
df['km_driven'] = df['km_driven'].str.replace("km","")
is_k = df['km_driven'].str.endswith('k', na=False)
df['km_driven'] = df['km_driven'].str.replace("k","")
df['km_driven'] = pd.to_numeric(df['km_driven'], errors='coerce')
df.loc[is_k, 'km_driven'] *= 1000

In [737]:
df['km_driven'].unique()

array([   70000.,    50000.,   100000.,    46000.,   141000.,       nan,
          60000.,    25000.,    78000.,   125000.,    35000.,    24000.,
           5000.,    33000.,    59000.,     4500.,    14500.,    33800.,
          80000.,    10000.,   119000.,    75800.,    40000.,    74000.,
          64000.,   120000.,    79000.,    15000.,    18500.,    10200.,
          29000.,    28000.,    90000.,    92000.,    66764.,   350000.,
         230000.,    39000.,   166000.,   110000.,    54000.,    63000.,
          11958.,    20000.,     9000.,     6500.,    58000.,    62200.,
          34000.,    53000.,    49000.,    21000.,    29173.,    30000.,
          87000.,    16000.,     3600.,    14272.,    57000.,     3240.,
         114000.,    53772.,   140000.,   175000.,   155500.,    22155.,
          78380.,   150000.,    80362.,    55000.,     1136.,    43000.,
           2650.,   115962.,    65000.,    56000.,   213000.,   139000.,
         160000.,   163000.,    32000.,    52000.,    11240.,    66000.,
          26500.,    72000.,    44000.,   130000.,   195000.,   155000.,
          41000.,    10832.,    14681.,    51000.,   200000.,    19600.,
          21170.,   167223.,   212814.,    88635.,   149674.,     8000.,
          68000.,    38000.,    98000.,    81925.,    97000.,    52047.,
          62009.,    33100.,   220000.,    45000.,   180000.,    22000.,
          80577.,   127500.,    40903.,    22288.,    61690.,    64484.,
          75976.,    85962.,    75000.,    57035.,    72104.,   164000.,
         124439.,    77000.,     1250.,    17152.,    24005.,   149000.,
          19000.,   109000.,    61000.,    27633.,    12586.,    38083.,
          55328.,    81632.,   155201.,    93283.,   217871.,    90165.,
         101504.,    86017.,    85036.,    91086.,   160254.,   125531.,
          84000.,   560000.,    14365.,    61083.,    66363.,    11700.,
          45974.,    55340.,    61585.,    39415.,    29654.,    64672.,
          54634.,    66521.,    23974.,     1000.,    86000.,    52600.,
          19890.,     7104.,    11918.,    10510.,    58500.,    56580.,
          46507.,    47162.,    49824.,    11451.,   172000.,    66508.,
          29900.,     3000.,    85000.,     7900.,    17500.,   206500.,
          88600.,   186000.,    11000.,    27974.,    18000.,     1400.,
         124000.,    42000.,    28205.,    32670.,    30093.,    56228.,
          59319.,    39503.,    35299.,    51687.,    76259.,    44049.,
          45087.,    41125.,    42215.,    52547.,    59110.,    54565.,
          47564.,    45143.,    61624.,   132000.,    20629.,    69782.,
          63654.,    59385.,    70378.,    55425.,    78413.,    40890.,
          34823.,    55545.,    56541.,    43700.,    27483.,    56207.,
           1440.,    91195.,    63657.,    97248.,    89000.,    36000.,
          12997.,    26430.,    24600.,    28481.,    41988.,    30375.,
           7658.,    34400.,    48000.,    28942.,    53652.,   106000.,
          82000.,    79500.,   197000.,     9161.,    19077.,   128000.,
          21302.,    10500.,   107000.,    55300.,    48781.,    87620.,
          40219.,    11473.,     8352.,     9745.,    31080.,    37605.,
          55850.,    58850.,    23839.,    45454.,    46957.,     1500.,
          47000.,   116000.,    26350.,    23000.,    71042.,    23038.,
          43608.,    11212.,    49217.,   190000.,   135000.,    19571.,
          29600.,    13500.,    48600.,   127643.,   102354.,    62237.,
          21394.,    32686.,     1001.,    53261.,    14000.,    39895.,
          73000.,    17000.,    18591.,    26766.,   300000.,    27620.,
         223000.,   161327.,     6000.,    71000.,   144000.,    37000.,
          26000.,    27000.,   101000.,     8500.,    90246.,    60400.,
           1100.,    31491.,   107143.,    46412.,    43826.,    55838.,
         112880.,    30300.,    80659.,    81324.,   127884.,    66755.,
         123084.,   806599.,    95851.,   234000.,   170000.,    96000.,
          19014.,    23262.,    35925.,    40771.,    55800.,    66569.,
          82695.,    68293.,   190621.,    88470.,    74183.,        1.,
         192000.,    83411.,    13270.,    88000.,    76000.,     7000.,
          13770.,   143000.,   115000.,   136906.,    28689.,    80322.,
          61658.,    30600.,   235000.,    12000.,    67000.,    74500.,
         118700.,     2000.,     4000.,    73756.,   185000.,    16400.,
          41395.,    71014.,   149500.,    83000.,    44800.,   156000.,
         146000.,    99000.,    25880.,   136000.,     2020.,    94000.,
          88500.,    52536.,     1950.,   118400.,     6480.,    32077.,
          19107.,    18469.,    28217.,    31063.,    79641.,    58692.,
          54784.,    64156.,     9500.,    81366.,   244000.,   312000.,
          52328.,    91505.,    20500.,   154000.,   133000.,    41723.,
          27289.,    28245.,    39227.,    31367.,    27005.,   100005.,
          45264.,    39093.,     2769.,    43128.,    22255.,    59213.,
           1010.,     1111.,     5166.,    76290.,    45766.,    78771.,
          79357.,    76736.,    92645.,   155836.,    63230.,     1452.,
          35122.,    92621.,    92198.,   152000.,    78322.,    13000.,
          54309.,    34600.,    31000.,    38217.,    77073.,    81257.,
           3917.,    69069.,    59059.,    55168.,    41041.,    67067.,
          66066.,    70070.,    63063., 50000000.,     9528.,   135200.,
          50300.,   151624.,    74820.,   129000.,    66778.,    63400.,
          38500.,   103921.,    43377.,   102307.,   245244.,    68500.,
           5007.,    49600.,    41123.,    20118.,    52517.,    99117.,
           3700.,    43500.,   137250.,     5400.,    11200.,    93000.,
          62000.,     5800.,   267000.,   250000.,    28635.,    95149.,
          68458.,   105546.,   104000.,   132343.,    26134.,    53600.,
          52895.,    42324.,    10300.,   142000.,     7600.,    47253.,
           4432.,    68523.,    80251.,    34500.,    42743.,    68745.,
          10980.,    35008.,   113600.,   138925.,   121764.,   105429.,
          44500.,    63500.,     9800.,    13599.,     5200.,    12700.,
          45839.,    74510.,    87293.,   156040.,    93415.,   101159.,
          68519.,    55130.,    58182.,   102989.,   178000.,    75118.,
           4637.,    95000.,    55766.,   117000.,   105000.,   182000.,
          24585.,    17563.,   173000.,   151000.,   117780.,    81595.,
           9700.,   221000.,    48500.,   148620.,    74300.,     9748.,
          20694.,   270000.,    41090.,   296823.,    89255.,   168000.,
           5550.,     1700.,    45217.,    44440.,    91365.,    90010.,
          31800.,    59100.,    31200.,    22700.,    50900.,     2417.,
          65500.,   140300.,    10211.,   145000.,   102000.,    32933.,
          54551.,    57112.,    41025.,    53122.,    64111.,    78892.,
          74113.,    84775.,    20778.,    64441.,    43192.,    44416.,
          79991.,    62601.,    60800.,    69111.,    81000.,    49213.,
          93900.,    20969.,    20194.,    34982.,    44588.,    57904.,
          59258.,    60826.,   109052.,    25552.,    40700.,    28838.,
          11174.,    72500.,    97700.,    37500.,    23800.,    44077.,
         210000.,     9422.,   224642.,   222435.,   159000.,   101100.,
         126000.,     1200.,   134444.,   238000.,   165000.,    63700.,
          74800.,  9999999.,    60516.,    76731.,    63840.,    76400.,
          31489.,   295000.,   158000.,   400000.,    19495.,    63356.,
         129627.,     4400.,    25061.,    42494.,    44875.,    89741.,
         347089.,   222252.,    55250.,    12500.,   162000.,    22038.,
           2500.,    89126.,   134000.,    42500.,   131365.,    48980.,
          13800.,    99700.,    49654.,    45457.,    39221.,    48220.,
          11114.,    60208.,    98600.,    85441.,    64541.,    16267.,
          71500.,    12999.,    14700.,    92686.,    49359.,   108731.,
          29976.,    30646.,    23600.,    71318.,    78098.,    18054.,
          38406.,    32260.,    73350.,    96987.,    77350.,    61187.,
          68350.,    81150.,   280000., 15000000.,   105700.,    37091.,
          38900.,     9400.,    14100.,    37555.,    56600.,    67580.,
          48238.,    38365.,    49834.,    57353.,    63240.,    69000.,
          64916.,    37161.,   118000.,    50852.,    53500.,    79800.,
          49957.,    43235.,    50699.,   140730.,   256000.,  8000000.,
         218000.,    43100.,    10171.,    66782.,   112198.])

In [738]:
df['km_driven'].describe()

count    3.607000e+03
mean     8.991722e+04
std      8.943338e+05
min      1.000000e+00
25%      3.500000e+04
50%      6.000000e+04
75%      9.000000e+04
max      5.000000e+07
Name: km_driven, dtype: float64

In [739]:
df['brand'] = df['name'].str.split().str[0]

In [740]:
df['brand'].value_counts()

brand
Maruti           1160
Hyundai           728
Tata              330
Mahindra          326
Honda             235
Ford              221
Toyota            186
Chevrolet         167
Renault           126
Volkswagen        102
Skoda              61
Nissan             57
Audi               46
Datsun             35
Fiat               35
BMW                34
Mercedes-Benz      26
Land                5
Mitsubishi          5
Jaguar              5
Volvo               4
Jeep                3
Ambassador          3
OpelCorsa           2
Daewoo              1
MG                  1
Force               1
Isuzu               1
Kia                 1
Name: count, dtype: int64

In [741]:
df['year'].describe()

count    3633.000000
mean     2013.034407
std         4.706610
min      1890.000000
25%      2011.000000
50%      2014.000000
75%      2016.000000
max      2020.000000
Name: year, dtype: float64

year is normally distributed, no outliers

In [742]:
df['selling_price'].describe()

count    3.634000e+03
mean     4.934202e+05
std      5.615647e+05
min      2.000000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

+ve skew (right skew)

In [743]:
iqr = 600000 - 200000
600000 + 1.5*iqr

1200000.0

In [744]:
df[df['selling_price'] > 1200000].sort_values('selling_price')

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
2404,Honda City i-VTEC CVT ZX,2018.0,1225000.0,22000.0,Petrol,Dealer,Automatic,First Owner,Honda
4228,Mahindra XUV500 W10 AWD,2015.0,1225000.0,70000.0,Diesel,Individual,Manual,First Owner,Mahindra
2718,Mahindra XUV500 AT W8 FWD,2017.0,1230000.0,70000.0,Diesel,Individual,Automatic,First Owner,Mahindra
2848,Honda WR-V i-DTEC VX,2019.0,1240000.0,13000.0,Diesel,Dealer,Manual,First Owner,Honda
4049,Hyundai Creta 1.6 CRDi SX Plus,2016.0,1249000.0,60000.0,Diesel,Individual,Manual,NaN,Hyundai
...,...,...,...,...,...,...,...,...,...
2239,BMW X5 xDrive 30d xLine,2019.0,4950000.0,30000.0,Diesel,Dealer,Automatic,First Owner,BMW
612,BMW X5 xDrive 30d xLine,2019.0,4950000.0,30000.0,NaN,Dealer,Automatic,First Owner,BMW
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016.0,5500000.0,77350.0,Diesel,Dealer,Automatic,First Owner,Mercedes-Benz
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017.0,8150000.0,6500.0,Diesel,Dealer,Automatic,First Owner,Mercedes-Benz
3872,Audi RS7 2015-2019 Sportback Performance,NaN,8900000.0,NaN,Petrol,Dealer,Automatic,First Owner,Audi

In [745]:
df['km_driven'].describe()

count    3.607000e+03
mean     8.991722e+04
std      8.943338e+05
min      1.000000e+00
25%      3.500000e+04
50%      6.000000e+04
75%      9.000000e+04
max      5.000000e+07
Name: km_driven, dtype: float64

extreme right skew due to an outlier

In [746]:
df[df['km_driven'] >= 1000000]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
2102,Datsun RediGO S,2016.0,270000.0,50000000.0,Petrol,Individual,Manual,NaN,Datsun
3594,Mahindra Scorpio VLX 2WD AIRBAG BSIV,2014.0,600000.0,9999999.0,Diesel,Individual,Manual,Second Owner,Mahindra
3984,Maruti Zen LX,NaN,85000.0,15000000.0,Petrol,Individual,Manual,Second Owner,Maruti
4218,Honda City i-DTEC VX,2017.0,1000000.0,8000000.0,Diesel,Individual,Manual,First Owner,Honda

In [747]:
df.loc[df['km_driven'] >= 1000000, 'km_driven'] = df['km_driven'].median()
df['km_driven'].describe()

count      3607.000000
mean      66972.948711
std       47675.973402
min           1.000000
25%       35000.000000
50%       60000.000000
75%       90000.000000
max      806599.000000
Name: km_driven, dtype: float64

In [748]:
df[df['km_driven'] < 100]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
1312,Mahindra Quanto C6,2014.0,250000.0,1.0,Diesel,Individual,Manual,Second Owner,Mahindra

In [749]:
x = 90000 - 35000
90000 + 1.5*x , 35000 - 1.5*x

(172500.0, -47500.0)

In [750]:
df[df['km_driven'] > 172500]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
69,Chevrolet Tavera Neo LS B3 - 7(C) seats BSIII,2010.0,280000.0,350000.0,Diesel,Individual,Manual,Second Owner,Chevrolet
70,Toyota Corolla Altis Diesel D4DG,2011.0,350000.0,230000.0,Diesel,Individual,Manual,First Owner,Toyota
159,Chevrolet Enjoy 1.3 TCDi LS 8,2015.0,NaN,175000.0,Diesel,Individual,Manual,First Owner,Chevrolet
197,Mahindra Xylo E4,2009.0,229999.0,230000.0,Diesel,NaN,Manual,NaN,Mahindra
225,Mahindra Renault Logan 1.5 DLS,2008.0,89999.0,213000.0,Diesel,Individual,Manual,First Owner,Mahindra
...,...,...,...,...,...,...,...,...,...
4231,Toyota Innova 2.5 G (Diesel) 8 Seater BS IV,2011.0,800000.0,230000.0,NaN,Individual,Manual,First Owner,Toyota
4255,Mahindra XUV500 W8 2WD,2014.0,650000.0,218000.0,Diesel,Individual,Manual,Second Owner,Mahindra
4275,Mahindra XUV500 W8 2WD,2014.0,650000.0,218000.0,NaN,Individual,Manual,Second Owner,Mahindra
4286,Fiat Punto 1.3 Emotion,2010.0,130000.0,210000.0,Diesel,Individual,Manual,Second Owner,Fiat
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015.0,530000.0,175000.0,Diesel,Individual,Manual,Third Owner,Ford

In [751]:
df['price_per_km'] = df['selling_price'] / df['km_driven']

In [752]:
df['age'] = 2026 - df['year']

In [753]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand,price_per_km,age
0,Maruti 800 AC,2007.0,NaN,70000.0,Petrol,NaN,Manual,First Owner,Maruti,NaN,19.0
1,Maruti Wagon R LXI Minor,NaN,135000.0,50000.0,Petrol,Individual,Manual,First Owner,Maruti,2.700000,NaN
2,Hyundai Verna 1.6 SX,2012.0,600000.0,100000.0,Diesel,Individual,Manual,First Owner,Hyundai,6.000000,14.0
3,Datsun RediGO T Option,2017.0,250000.0,46000.0,Petrol,Individual,Manual,First Owner,Datsun,5.434783,9.0
4,Honda Amaze VX i-DTEC,2014.0,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,Honda,3.191489,12.0
...,...,...,...,...,...,...,...,...,...,...,...
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,NaN,600000.0,170000.0,Diesel,Individual,Manual,NaN,Toyota,3.529412,NaN
4336,Hyundai i20 Magna 1.4 CRDi,2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner,Hyundai,5.124987,12.0
4337,Maruti 800 AC BSIII,2009.0,110000.0,83000.0,Petrol,Individual,Manual,Second Owner,Maruti,1.325301,17.0
4338,Hyundai Creta 1.6 CRDi SX Option,2016.0,865000.0,90000.0,Diesel,Individual,Manual,First Owner,Hyundai,9.611111,10.0
4339,Renault KWID RXT,2016.0,225000.0,40000.0,Petrol,Individual,Manual,First Owner,Renault,5.625000,10.0

In [754]:
df['name'].describe()

count                       3907
unique                      1438
top       Maruti Swift Dzire VDI
freq                          63
Name: name, dtype: object

In [755]:
df['name'].value_counts()

name
Maruti Swift Dzire VDI        63
Maruti Alto 800 LXI           49
Maruti Alto LXi               44
Maruti Alto LX                34
Hyundai EON Era Plus          30
                              ..
Maruti S-Presso VXI Plus       1
Toyota Etios Liva 1.2 VX       1
Toyota Yaris G                 1
Maruti Swift LXI Option        1
Hyundai i20 Magna 1.4 CRDi     1
Name: count, Length: 1438, dtype: int64

In [756]:
df['fuel'].describe()

count       3632
unique         5
top       Petrol
freq        1789
Name: fuel, dtype: object

In [757]:
df['fuel'].value_counts()

fuel
Petrol      1789
Diesel      1782
CNG           39
LPG           21
Electric       1
Name: count, dtype: int64

In [758]:
df['seller_type'].describe()

count           3648
unique             3
top       Individual
freq            2765
Name: seller_type, dtype: object

In [759]:
df['seller_type'].value_counts()

seller_type
Individual          2765
Dealer               818
Trustmark Dealer      65
Name: count, dtype: int64

In [760]:
df['transmission'].describe()

count       3626
unique         2
top       Manual
freq        3251
Name: transmission, dtype: object

In [761]:
df['transmission'].value_counts()

transmission
Manual       3251
Automatic     375
Name: count, dtype: int64

In [762]:
df["owner"].describe()

count            3643
unique              5
top       First Owner
freq             2364
Name: owner, dtype: object

In [763]:
df["owner"].value_counts()

owner
First Owner             2364
Second Owner             935
Third Owner              264
Fourth & Above Owner      67
Test Drive Car            13
Name: count, dtype: int64

In [764]:
df['brand'].describe()

count       3907
unique        29
top       Maruti
freq        1160
Name: brand, dtype: object

In [765]:
df['brand'].value_counts()

brand
Maruti           1160
Hyundai           728
Tata              330
Mahindra          326
Honda             235
Ford              221
Toyota            186
Chevrolet         167
Renault           126
Volkswagen        102
Skoda              61
Nissan             57
Audi               46
Datsun             35
Fiat               35
BMW                34
Mercedes-Benz      26
Land                5
Mitsubishi          5
Jaguar              5
Volvo               4
Jeep                3
Ambassador          3
OpelCorsa           2
Daewoo              1
MG                  1
Force               1
Isuzu               1
Kia                 1
Name: count, dtype: int64

In [766]:
df['age'].describe()

count    3633.000000
mean       12.965593
std         4.706610
min         6.000000
25%        10.000000
50%        12.000000
75%        15.000000
max       136.000000
Name: age, dtype: float64

max 136 because of min year 1890

In [767]:
df['age'].corr(df['selling_price'], method='spearman')

np.float64(-0.7033973230199019)

In [768]:
df[['selling_price', 'age', 'km_driven']].corr(method='spearman')

               selling_price       age  km_driven
selling_price       1.000000 -0.703397  -0.319938
age                -0.703397  1.000000   0.563341
km_driven          -0.319938  0.563341   1.000000

In [769]:
x = df.groupby('fuel')['selling_price'].agg(['mean','median', 'count']).round(2)
x['overall'] = (x['median'] / df['selling_price'].median()).round(2)
x.sort_values('median', ascending=False)

               mean    median  count  overall
fuel
Diesel    650993.28  495000.0   1646     1.41
Electric  310000.00  310000.0      1     0.89
Petrol    347592.02  270000.0   1674     0.77
CNG       275472.14  237499.5     36     0.68
LPG       156904.71  170000.0     21     0.49

In [770]:
pd.crosstab(df['fuel'], df['transmission'], normalize='index').round(2)

transmission  Automatic  Manual
fuel
CNG                0.00    1.00
Diesel             0.12    0.88
Electric           1.00    0.00
LPG                0.00    1.00
Petrol             0.09    0.91

In [771]:
df.groupby(['fuel', 'transmission'])['selling_price'].median().unstack()

transmission  Automatic    Manual
fuel
CNG                 NaN  229999.0
Diesel        1477500.0  450000.0
Electric       310000.0       NaN
LPG                 NaN  155000.0
Petrol         520000.0  250000.0

In [772]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [773]:
model_cols = ['selling_price', 'age', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']

df_model = df[model_cols].dropna()

X = pd.get_dummies(
    df_model.drop(columns=['selling_price']),
    columns=['fuel', 'seller_type', 'transmission', 'owner'],
    drop_first=True
)
y = df_model['selling_price']

print(X.shape)
X.head()

(2345, 13)

,age,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
2,14.0,100000.0,True,False,False,False,True,False,True,False,False,False,False
3,9.0,46000.0,False,False,False,True,True,False,True,False,False,False,False
4,12.0,141000.0,True,False,False,False,True,False,True,False,True,False,False
7,12.0,60000.0,False,False,False,True,True,False,True,False,True,False,False
8,11.0,25000.0,False,False,False,True,True,False,True,False,False,False,False

In [774]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

1.2.regularization

In [775]:
models = {
    'Linear Regression': LinearRegression(),
    'Ridge (alpha=1.0)': Ridge(alpha=1.0),
    'Lasso (alpha=1.0)': Lasso(alpha=1.0)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    rmse = root_mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append({'Model': name, 'RMSE': rmse, 'R2': r2})

results_df = pd.DataFrame(results)
results_df

               Model           RMSE        R2
0  Linear Regression  383537.200323  0.538324
1  Ridge (alpha=1.0)  383516.728695  0.538373
2  Lasso (alpha=1.0)  383387.045522  0.538685

1.3. multicollinearity

In [776]:
correlation_matrix = df_model[['selling_price', 'age', 'km_driven']].corr()
correlation_matrix

               selling_price       age  km_driven
selling_price       1.000000 -0.415402  -0.171408
age                -0.415402  1.000000   0.400272
km_driven          -0.171408  0.400272   1.000000

In [777]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
X_numeric = df.select_dtypes(include=[np.number]).drop(columns=['selling_price'])
X_numeric = X_numeric.dropna()
vif_data = pd.DataFrame()
vif_data["feature"] = X_numeric.columns
vif_data["VIF"] = [variance_inflation_factor(X_numeric.values, i) for i in range(X_numeric.shape[1]) ]
print(vif_data.sort_values("VIF", ascending = False))

        feature           VIF
0          year  1.000800e+15
3           age  1.000800e+15
1     km_driven  1.201122e+00
2  price_per_km  1.000912e+00

/var/folders/4t/vf_2ms0d2392cg2kk_48w58r0000gn/T/ipykernel_8902/4085640049.py:6: UserWarning: The design matrix is poorly conditioned (condition number=1.72e+14). VIF calculations may be numerically unstable.
  vif_data["VIF"] = [variance_inflation_factor(X_numeric.values, i) for i in range(X_numeric.shape[1]) ]

1.4. feature scaling

In [778]:
scaler = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

standard_scaler = StandardScaler()
X_train_std = standard_scaler.fit_transform(X_train) 
X_test_std = standard_scaler.transform(X_test)

minmax_scaler = MinMaxScaler()
X_train_mm = minmax_scaler.fit_transform(X_train)
X_test_mm = minmax_scaler.transform(X_test)
X_train_scaled = scaler.fit_transform(X_train)  
X_test_scaled = scaler.transform(X_test)

part2

In [783]:
print(f"head: \n{df.head()}\n")
print(f"info: \n{df.info()}\n")
print(f"describe: \n{df.describe()}\n")
print(f"null\n{df.isnull().sum()}\n")
print(f"duplicates\n{df.duplicated().sum()}\n")

head:
                       name    year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007.0            NaN    70000.0  Petrol
1  Maruti Wagon R LXI Minor     NaN       135000.0    50000.0  Petrol
2      Hyundai Verna 1.6 SX  2012.0       600000.0   100000.0  Diesel
3    Datsun RediGO T Option  2017.0       250000.0    46000.0  Petrol
4     Honda Amaze VX i-DTEC  2014.0       450000.0   141000.0  Diesel

  seller_type transmission         owner    brand  price_per_km   age
0         NaN       Manual   First Owner   Maruti           NaN  19.0
1  Individual       Manual   First Owner   Maruti      2.700000   NaN
2  Individual       Manual   First Owner  Hyundai      6.000000  14.0
3  Individual       Manual   First Owner   Datsun      5.434783   9.0
4  Individual       Manual  Second Owner    Honda      3.191489  12.0

<class 'pandas.core.frame.DataFrame'>
Index: 3907 entries, 0 to 4339
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           3907 non-null   object
 1   year           3633 non-null   float64
 2   selling_price  3634 non-null   float64
 3   km_driven      3607 non-null   float64
 4   fuel           3632 non-null   object
 5   seller_type    3648 non-null   object
 6   transmission   3626 non-null   object
 7   owner          3643 non-null   object
 8   brand          3907 non-null   object
 9   price_per_km   3354 non-null   float64
 10  age            3633 non-null   float64
dtypes: float64(5), object(6)
memory usage: 366.3+ KB
info:
None

describe:
              year  selling_price      km_driven   price_per_km          age
count  3633.000000   3.634000e+03    3607.000000    3354.000000  3633.000000
mean   2013.034407   4.934202e+05   66972.948711      98.503785    12.965593
std       4.706610   5.615647e+05   47675.973402    4317.385929     4.706610
min    1890.000000   2.000000e+04       1.000000       0.250000     6.000000
25%    2011.000000   2.000000e+05   35000.000000       2.515498    10.000000
50%    2014.000000   3.500000e+05   60000.000000       6.000000    12.000000
75%    2016.000000   6.000000e+05   90000.000000      15.382212    15.000000
max    2020.000000   8.900000e+06  806599.000000  250000.000000   136.000000

null
name               0
year             274
selling_price    273
km_driven        300
fuel             275
seller_type      259
transmission     281
owner            264
brand              0
price_per_km     553
age              274
dtype: int64

duplicates
201

In [784]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [785]:
numeric_features = ['age', 'km_driven']
categorical_features = ['fuel', 'seller_type', 'transmission', 'owner']

In [789]:
model_cols = ['selling_price', 'age', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']
df_model = df[model_cols].dropna()
X = df_model.drop(columns='selling_price')
y = df_model['selling_price']
df_model.shape

(2345, 7)

In [790]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=42)
X_train.shape, X_test.shape

((1876, 6), (469, 6))

In [791]:
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numeric_features),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
])

In [792]:
preprocessor.fit(X_train)
X_train_encoded = preprocessor.transform(X_train)
encoded_columns = numeric_features + list(
    preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features)
)
X_train_df = pd.DataFrame(X_train_encoded, columns=encoded_columns)
for col in X_train_df.columns:
    other_cols = X_train_df.drop(columns=col)
    r2 = LinearRegression().fit(other_cols, X_train_df[col]).score(other_cols, X_train_df[col])
    vif = 1 / (1 - r2) if r2 < 0.9999 else np.inf
    print(col, round(vif, 2))

age 1.48
km_driven 1.37
fuel_Diesel 22.16
fuel_Electric 1.06
fuel_LPG 1.5
fuel_Petrol 22.18
seller_type_Individual 1.16
seller_type_Trustmark Dealer 1.06
transmission_Manual 1.06
owner_Fourth & Above Owner 1.08
owner_Second Owner 1.24
owner_Test Drive Car 1.03
owner_Third Owner 1.17

In [793]:
model_1 = LinearRegression()
pipeline_1 = Pipeline([('preprocessing', preprocessor), ('model', model_1)])
pipeline_1.fit(X_train, y_train)
pred_1 = pipeline_1.predict(X_test)

model_2 = Ridge(alpha=1.0)
pipeline_2 = Pipeline([('preprocessing', preprocessor), ('model', model_2)])
pipeline_2.fit(X_train, y_train)
pred_2 = pipeline_2.predict(X_test)

model_3 = RandomForestRegressor(n_estimators=200, max_depth=8, random_state=42)
pipeline_3 = Pipeline([('preprocessing', preprocessor), ('model', model_3)])
pipeline_3.fit(X_train, y_train)
pred_3 = pipeline_3.predict(X_test)

In [795]:
def evaluate(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2 = r2_score(y_true, y_pred)
    return mae, rmse, r2

mae_1, rmse_1, r2_1 = evaluate(y_test, pred_1)
mae_2, rmse_2, r2_2 = evaluate(y_test, pred_2)
mae_3, rmse_3, r2_3 = evaluate(y_test, pred_3)

comparison_table = pd.DataFrame({
    'Model': ['Linear Regression', 'Ridge (alpha=1.0)', 'Random Forest'],
    'MAE':  [mae_1, mae_2, mae_3],
    'RMSE': [rmse_1, rmse_2, rmse_3],
    'R2':   [r2_1, r2_2, r2_3]
})
comparison_table

               Model            MAE           RMSE        R2
0  Linear Regression  229603.224104  383387.859325  0.538684
1  Ridge (alpha=1.0)  229535.689538  383519.004711  0.538368
2      Random Forest  190640.405242  353938.202123  0.606833

Which model performed best?
Random Forest as it has the lowest MAE, RMSE and highst R square which provided the strongest predictive performance on the test set

Did regularization improve the results? NO, linear regression are almost the same .

Did scaling affect the models, and why? Yes for Linear reg and Ridge as there is a huge difference between age and km_driven values so age may come out larger, scaleing both means = 0, std = 1 removes this problem. scaling didn't affect random forest as it is threshold-based splitting.

Did you find evidence of multicollinearity? yes in fuel_petrol and diesel because together they cover 97% of the dataset.

Which model would you choose for this problem and why? Random Forest for the raw predictive accuracy